-- ============================================================================
-- GearScore - TurtleLootLine Addon
-- Syncs equipped gear to desktop companion and displays upgrade recommendations
-- ============================================================================

-- Saved data (written to WTF folder)
GearScoreData = GearScoreData or {}

-- Upgrade data (generated by Electron companion)
GearScoreUpgrades = GearScoreUpgrades or {}

-- Wanted items list (generated by Electron companion)
GearScore_WantedItems = GearScore_WantedItems or {}

-- Slot IDs to slot names mapping
local SLOT_NAMES = {
    [1] = "Head",
    [2] = "Neck",
    [3] = "Shoulder",
    [4] = "Shirt",
    [5] = "Chest",
    [6] = "Waist",
    [7] = "Legs",
    [8] = "Feet",
    [9] = "Wrist",
    [10] = "Hands",
    [11] = "Finger1",
    [12] = "Finger2",
    [13] = "Trinket1",
    [14] = "Trinket2",
    [15] = "Back",
    [16] = "MainHand",
    [17] = "OffHand",
    [18] = "Ranged",
    [19] = "Tabard"
}

-- Create main event frame
local frame = CreateFrame("Frame")

-- ============================================================================
-- UTILITY FUNCTIONS
-- ============================================================================

local function Print(msg)
    DEFAULT_CHAT_FRAME:AddMessage("|cFF00FF00[GearScore]|r " .. msg)
end

-- Print only when debug logging is enabled in settings
local function PrintDebug(msg)
    if GearScoreSettings and GearScoreSettings.debugLog == false then return end
    DEFAULT_CHAT_FRAME:AddMessage("|cFF00FF00[GearScore]|r " .. msg)
end

local function PrintError(msg)
    DEFAULT_CHAT_FRAME:AddMessage("|cFFFF0000[GearScore]|r " .. msg)
end

-- ============================================================================
-- EQUIPMENT SCANNING
-- ============================================================================

-- Extract item name from item link
local function GetItemNameFromLink(itemLink)
    if not itemLink or type(itemLink) ~= "string" or itemLink == "" then
        return nil
    end

    -- Item link format: |cXXXXXXXX|Hitem:id:...|h[Item Name]|h|r
    local _, _, itemName = string.find(itemLink, "%[(.+)%]")
    return itemName
end

-- Scan all equipped gear and return equipment table
local function ScanEquipment()
    local equipment = {}

    for slotId = 1, 19 do
        local itemLink = GetInventoryItemLink("player", slotId)

        if itemLink then
            local _, _, itemIdStr = string.find(itemLink, "item:(%d+)")
            local itemId = tonumber(itemIdStr)

            -- Extract name from link (more reliable than GetItemInfo in Vanilla)
            local itemName = GetItemNameFromLink(itemLink)

            -- Fallback to GetItemInfo if link parsing failed
            if not itemName then
                itemName = GetItemInfo(itemLink)
            end

            if itemId then
                local entry = {
                    slot = SLOT_NAMES[slotId],
                    itemId = itemId,
                    itemName = itemName or ("Item #" .. itemId),
                    itemLink = itemLink
                }

                -- Enchant ID is the second field of the link: item:id:enchant:suffix:unique
                local _, _, enchantIdStr = string.find(itemLink, "item:%d+:(%d+)")
                local enchantId = tonumber(enchantIdStr)
                if enchantId and enchantId > 0 then
                    entry.enchantId = enchantId
                    -- Reading the tooltip must never block the save, so guard it
                    if GearScore_GetEquippedEnchantText then
                        local ok, text = pcall(GearScore_GetEquippedEnchantText, slotId)
                        if ok then
                            entry.enchantText = text
                        else
                            PrintError("Enchant text read failed for slot " .. slotId .. ": " .. tostring(text))
                        end
                    end
                end

                equipment[slotId] = entry
            end
        end
    end

    return equipment
end

-- ============================================================================
-- TALENT SCANNING
-- ============================================================================

-- Scan current talent build and return a signature + tree data
-- Returns nil if talent data isn't loaded yet (no tabs, or every maxRank is 0)
local function ScanTalents()
    local numTabs = GetNumTalentTabs()
    if not numTabs or numTabs == 0 then
        return nil
    end

    local trees = {}
    local summary = {}
    local totalMaxRank = 0
    for tab = 1, numTabs do
        local tabName = GetTalentTabInfo(tab)
        local points = 0
        local talents = {}
        for i = 1, GetNumTalents(tab) do
            local name, iconTexture, tier, column, rank, maxRank = GetTalentInfo(tab, i)
            talents[i] = { name = name, rank = rank, maxRank = maxRank }
            points = points + (rank or 0)
            totalMaxRank = totalMaxRank + (maxRank or 0)
        end
        trees[tab] = { name = tabName, points = points, talents = talents }
        table.insert(summary, tostring(points))
    end

    if totalMaxRank == 0 then
        return nil
    end

    local signature = table.concat(summary, "/")  -- e.g. "21/30/0"
    return signature, trees
end

-- A stored build is valid if it has a signature and at least one talent with maxRank > 0
local function IsValidTalentBuild(sig, build)
    if not sig or sig == "" or not build or not build.trees then
        return false
    end
    for _, tree in pairs(build.trees) do
        if tree.talents then
            for _, talent in pairs(tree.talents) do
                if talent.maxRank and talent.maxRank > 0 then
                    return true
                end
            end
        end
    end
    return false
end

-- Drop builds saved before talent data had loaded (e.g. "" or all-zero maxRank)
local function PruneTalentBuilds(builds)
    local cleaned = {}
    if builds then
        for sig, build in pairs(builds) do
            if IsValidTalentBuild(sig, build) then
                cleaned[sig] = build
            end
        end
    end
    return cleaned
end

-- ============================================================================
-- DATA PERSISTENCE
-- ============================================================================

-- Throttle SaveData to prevent spam
local lastSaveTime = 0
local SAVE_THROTTLE = 2  -- Only save once per 2 seconds

-- Cache talent builds across saves (SaveData overwrites GearScoreData entirely)
local cachedTalentBuilds = {}

-- Set while logging out / reloading: game data is already unloaded, so never save then
local isLeavingWorld = false

-- Delayed rescan when level/talents weren't ready yet
local RESCAN_DELAY = 5      -- seconds
local MAX_RESCANS = 6
local rescanTimer = nil     -- seconds until next rescan, nil = none scheduled
local rescanCount = 0

local function ScheduleRescan()
    if rescanCount < MAX_RESCANS and not rescanTimer then
        rescanTimer = RESCAN_DELAY
    end
end

-- Save current gear data to SavedVariables
local function SaveData(forceDebug)
    if isLeavingWorld then
        return
    end

    -- Throttle to prevent excessive saves
    local currentTime = time()
    if currentTime - lastSaveTime < SAVE_THROTTLE then
        if forceDebug then
            Print("SaveData throttled (wait " .. (SAVE_THROTTLE - (currentTime - lastSaveTime)) .. " seconds)")
        end
        return
    end
    lastSaveTime = currentTime

    local previous = GearScoreData or {}

    -- Preserve existing talent builds before overwriting (dropping any broken ones)
    if previous.talents and previous.talents.builds then
        cachedTalentBuilds = PruneTalentBuilds(previous.talents.builds)
    end

    local equipment = ScanEquipment()
    local needsRescan = false

    -- Level can read 0 before the player is fully loaded; keep the last good value
    local level = UnitLevel("player")
    if not level or level <= 0 then
        if previous.level and previous.level > 0 then
            level = previous.level
        else
            level = nil
        end
        needsRescan = true
    end

    GearScoreData = {
        lastUpdated = time(),
        character = UnitName("player"),
        realm = GetRealmName(),
        class = UnitClass("player"),
        race = UnitRace("player"),
        level = level,
        guild = GetGuildInfo("player"),
        equipment = equipment
    }

    -- Add talent data if enabled
    if not GearScoreSettings or GearScoreSettings.talentsEnabled ~= false then
        local sig, trees = ScanTalents()
        local active

        if sig then
            cachedTalentBuilds[sig] = {
                timestamp = time(),
                trees = trees
            }
            active = sig
        else
            -- Talent data not loaded yet: keep the last known active build
            if previous.talents and IsValidTalentBuild(previous.talents.active, cachedTalentBuilds[previous.talents.active]) then
                active = previous.talents.active
            end
            needsRescan = true
        end

        GearScoreData.talents = {
            active = active,
            builds = cachedTalentBuilds
        }

        if forceDebug then
            local buildCount = 0
            for _ in pairs(cachedTalentBuilds) do
                buildCount = buildCount + 1
            end
            PrintDebug(string.format("Active talents: %s (%d build(s) stored)", tostring(active), buildCount))
        end
    end

    if needsRescan then
        ScheduleRescan()
    end

    -- Debug: count equipped items
    local count = 0
    for _ in pairs(equipment) do
        count = count + 1
    end

    if forceDebug then
        PrintDebug(string.format("Saved %d equipped items to GearScoreData", count))
        PrintDebug(string.format("Character: %s (%s)", UnitName("player"), GetRealmName()))
    end
end

-- ============================================================================
-- GLOBAL API (called by GearScoreUI)
-- ============================================================================

function GearScore_ManualScan()
    SaveData(true)
    Print("Manual scan complete!")
end

function GearScore_ShowLootList()
    if not GearScoreLootDB or not GearScoreLootDB.items then
        Print("Loot database not initialized")
        return
    end
    Print("--- All Collected Items ---")
    local count = 0
    local qualityColors = {
        [0] = "|cFF9D9D9D",
        [1] = "|cFFFFFFFF",
        [2] = "|cFF1EFF00",
        [3] = "|cFF0070DD",
        [4] = "|cFFA335EE",
        [5] = "|cFFFF8000",
    }
    for itemId, item in pairs(GearScoreLootDB.items) do
        count = count + 1
        local color = qualityColors[item.quality] or "|cFFFFFFFF"
        local slot = item.equipSlot or item.armorType or "?"
        Print(string.format("  %s[%d] %s|r - %s", color, itemId, item.name or "?", slot))
    end
    Print(string.format("Total: %d items", count))
end

function GearScore_ShowLootDBStats()
    if not GearScoreLootDB then
        Print("Loot database not initialized")
        return
    end
    local count = GearScore_GetLootDBCount and GearScore_GetLootDBCount() or 0
    Print("--- Loot Database ---")
    Print(string.format("Items collected: %d", count))
    Print(string.format("DB version: %s", tostring(GearScoreLootDB.version or "N/A")))
    if GearScoreLootDB.lastUpdated and GearScoreLootDB.lastUpdated > 0 then
        Print(string.format("Last updated: %d seconds ago", time() - GearScoreLootDB.lastUpdated))
    end
end

-- ============================================================================
-- EVENT HANDLERS
-- ============================================================================

-- Main event handler
local function OnEvent()
    if event == "PLAYER_ENTERING_WORLD" then
        -- Player logged in or entered world
        isLeavingWorld = false
        rescanCount = 0

        -- Force a save immediately on login (bypass throttle)
        lastSaveTime = 0  -- Reset throttle
        SaveData(true)     -- Enable debug output

        -- Gear, level and talents may not be loaded yet; scan again shortly
        ScheduleRescan()

        -- Show upgrade count if available
        local upgradeCount = 0
        for _ in pairs(GearScoreUpgrades) do
            upgradeCount = upgradeCount + 1
        end

        if upgradeCount > 0 then
            PrintDebug(string.format("Loaded upgrade data for %d items", upgradeCount))
        else
            PrintDebug("Tip: Desktop companion will sync upgrade data")
        end

    elseif event == "UNIT_INVENTORY_CHANGED" then
        -- Inventory changed (includes equipment changes in Vanilla)
        local unit = arg1
        if unit == "player" then
            SaveData()
        end

    elseif event == "CHARACTER_POINTS_CHANGED" then
        -- Talent points changed (learned or reset talents)
        if not GearScoreSettings or GearScoreSettings.talentsEnabled ~= false then
            SaveData()
        end

    elseif event == "PLAYER_LEAVING_WORLD" then
        -- About to logout/reload. Equipment, level and talents are already unloaded
        -- here, so saving now would wipe good data. GearScoreData already holds the
        -- last good scan and WoW writes it to disk on its own.
        isLeavingWorld = true
        rescanTimer = nil
    end
end

frame:SetScript("OnEvent", OnEvent)

-- Delayed rescan timer (Vanilla 1.12: arg1 = elapsed seconds)
frame:SetScript("OnUpdate", function()
    if not rescanTimer then return end
    rescanTimer = rescanTimer - arg1
    if rescanTimer > 0 then return end

    rescanTimer = nil
    rescanCount = rescanCount + 1
    lastSaveTime = 0  -- bypass throttle
    SaveData()
end)

-- Register events (Vanilla 1.12 compatible)
frame:RegisterEvent("PLAYER_ENTERING_WORLD")
frame:RegisterEvent("PLAYER_LEAVING_WORLD")
frame:RegisterEvent("UNIT_INVENTORY_CHANGED")
frame:RegisterEvent("CHARACTER_POINTS_CHANGED")

-- ============================================================================
-- TOOLTIP HOOK FOR UPGRADE DISPLAY
-- ============================================================================

-- Get color code for stat change
local function GetStatColor(value)
    if not value then return "|cFFFFFFFF" end

    local str = tostring(value)
    if string.sub(str, 1, 1) == "+" then
        return "|cFF00FF00"  -- Green for positive
    elseif string.sub(str, 1, 1) == "-" then
        return "|cFFFF0000"  -- Red for negative
    else
        return "|cFFFFFFFF"  -- White for neutral
    end
end

-- Format stat name for display
local function FormatStatName(statKey)
    if not statKey or type(statKey) ~= "string" then
        return "Unknown"
    end

    -- Convert camelCase to readable format
    local formatted = string.gsub(statKey, "([a-z])([A-Z])", "%1 %2")
    -- Capitalize first letter
    return string.upper(string.sub(formatted, 1, 1)) .. string.sub(formatted, 2)
end

-- Track current tooltip item link (vanilla 1.12 has no tooltip:GetItem())
local currentTooltipItemLink = nil
local lastTooltipItem = nil

-- Resolve item link from tooltip by reading its name and matching via GetItemInfo
-- This avoids hooking any tooltip Set* methods which can break return values
local function ResolveTooltipItemLink(tooltip)
    local textLeft1 = tooltip:GetName() and getglobal(tooltip:GetName() .. "TextLeft1")
    if not textLeft1 then return nil end

    local itemName = textLeft1:GetText()
    if not itemName or itemName == "" then return nil end

    -- Try to find this item by scanning equipped slots first (most common tooltip case)
    for slotId = 1, 19 do
        local link = GetInventoryItemLink("player", slotId)
        if link then
            local _, _, name = string.find(link, "%[(.+)%]")
            if name == itemName then
                return link
            end
        end
    end

    -- Try bag items
    for bag = 0, 4 do
        local numSlots = GetContainerNumSlots(bag)
        if numSlots then
            for slot = 1, numSlots do
                local link = GetContainerItemLink(bag, slot)
                if link then
                    local _, _, name = string.find(link, "%[(.+)%]")
                    if name == itemName then
                        return link
                    end
                end
            end
        end
    end

    return nil
end

-- Add upgrade data to tooltip
local function AddUpgradeDataToTooltip(tooltip)
    local itemLink = ResolveTooltipItemLink(tooltip)
    if not itemLink then
        lastTooltipItem = nil
        return
    end

    -- Extract item ID from link
    local _, _, itemIdStr = string.find(itemLink, "item:(%d+)")
    if not itemIdStr then return end

    local itemId = tonumber(itemIdStr)
    if not itemId then return end

    -- Prevent duplicate additions (check if we already added our lines)
    if lastTooltipItem == itemId then return end

    -- Check if we have upgrade data for this item
    local upgrade = GearScoreUpgrades[itemId]
    if not upgrade then
        lastTooltipItem = itemId  -- Still mark as checked to avoid re-scanning
        return
    end

    lastTooltipItem = itemId

    -- Skip if item is the same as equipped (overall +0% with no other stats)
    if upgrade.overall == "+0%" then
        local hasStats = false
        for k, v in pairs(upgrade) do
            if k ~= "overall" and k ~= "note" then
                hasStats = true
                break
            end
        end
        if not hasStats then return end
    end

    -- Add separator
    tooltip:AddLine(" ")
    tooltip:AddLine("|cFF00BFFF⚔ TurtleLootLine:|r")

    -- Display stats in order: stamina, armor, strength, agility, etc., then overall
    local statsOrder = {
        "stamina", "armor", "strength", "agility", "intellect", "spirit",
        "defense", "attackPower", "spellPower", "healing", "hitRating",
        "critRating", "hasteRating", "dodgeRating", "parryRating", "blockRating"
    }

    for _, statKey in ipairs(statsOrder) do
        local value = upgrade[statKey]
        if value then
            local color = GetStatColor(value)
            local statName = FormatStatName(statKey)
            tooltip:AddLine("  " .. statName .. ": " .. color .. value .. "|r")
        end
    end

    -- Overall stat (highlighted in gold)
    if upgrade.overall then
        local color = GetStatColor(upgrade.overall)
        tooltip:AddLine("  |cFFFFD700Overall: " .. color .. upgrade.overall .. "|r")
    end

    -- Note (if available)
    if upgrade.note then
        tooltip:AddLine("  |cFFAAAAAA" .. upgrade.note .. "|r")
    end

    -- Refresh tooltip to update size
    tooltip:Show()
end

-- Hook GameTooltip:Show() to inject upgrade data (Vanilla 1.12 compatible)
local origGameTooltipShow = GameTooltip.Show
GameTooltip.Show = function(self)
    origGameTooltipShow(self)
    AddUpgradeDataToTooltip(self)
end

-- Reset tracking when tooltip hides
local origGameTooltipHide = GameTooltip.Hide
GameTooltip.Hide = function(self)
    lastTooltipItem = nil
    origGameTooltipHide(self)
end

-- Also hook ItemRefTooltip (for chat links)
local origItemRefShow = ItemRefTooltip.Show
ItemRefTooltip.Show = function(self)
    origItemRefShow(self)
    AddUpgradeDataToTooltip(self)
end

local origItemRefHide = ItemRefTooltip.Hide
ItemRefTooltip.Hide = function(self)
    lastTooltipItem = nil
    origItemRefHide(self)
end

-- ============================================================================
-- SLASH COMMANDS
-- ============================================================================

local function HandleSlashCommand(msg)
    msg = string.lower(msg or "")

    if msg == "scan" or msg == "s" then
        SaveData(true)  -- Pass true to enable debug output
        Print("Manual scan complete!")

    elseif msg == "stats" or msg == "stat" then
        -- Show statistics
        local equipment = ScanEquipment()
        local equippedCount = 0
        for _ in pairs(equipment) do
            equippedCount = equippedCount + 1
        end

        local upgradeCount = 0
        for _ in pairs(GearScoreUpgrades) do
            upgradeCount = upgradeCount + 1
        end

        Print("--- Statistics ---")
        Print(string.format("Equipped items: %d", equippedCount))
        Print(string.format("Upgrade data loaded: %d items", upgradeCount))

        if GearScoreData.lastUpdated then
            local timeSince = time() - GearScoreData.lastUpdated
            Print(string.format("Last scan: %d seconds ago", timeSince))
        end

    elseif msg == "clear" then
        -- Clear saved data
        GearScoreData = {}
        Print("Saved data cleared")

    elseif msg == "upgrades" then
        -- List items with upgrade data
        Print("--- Items with Upgrade Data ---")
        local count = 0
        for itemId, data in pairs(GearScoreUpgrades) do
            count = count + 1

            -- Ensure itemId is a number
            local numericItemId = tonumber(itemId)
            if not numericItemId then
                Print("Warning: Invalid item ID: " .. tostring(itemId))
            else
                -- Try to get item name, with fallback to ID if not cached
                local itemName = GetItemInfo(numericItemId)
                if not itemName then
                    itemName = "Item #" .. numericItemId
                end

                local overall = data.overall or "N/A"
                Print(string.format("%s: %s", itemName, overall))
            end

            if count >= 10 then
                local totalCount = 0
                for _ in pairs(GearScoreUpgrades) do
                    totalCount = totalCount + 1
                end
                Print(string.format("... and %d more items", totalCount - 10))
                break
            end
        end

        if count == 0 then
            Print("No upgrade data loaded")
        end

    elseif msg == "debug" or msg == "d" then
        -- Show debug information
        Print("--- Debug Information ---")

        if not GearScoreData or not GearScoreData.character then
            Print("|cFFFF0000GearScoreData is empty or not initialized!|r")
            Print("Try running: /gs scan")
        else
            Print(string.format("Character: %s", GearScoreData.character or "nil"))
            Print(string.format("Realm: %s", GearScoreData.realm or "nil"))
            Print(string.format("Class: %s", GearScoreData.class or "nil"))
            Print(string.format("Last Updated: %s", GearScoreData.lastUpdated or "nil"))

            if GearScoreData.equipment then
                local count = 0
                for slotId, item in pairs(GearScoreData.equipment) do
                    count = count + 1
                end
                Print(string.format("Equipment slots: %d", count))

                -- Show first few items as examples
                local shown = 0
                for slotId, item in pairs(GearScoreData.equipment) do
                    if shown < 3 then
                        Print(string.format("  [%d] %s (%s)", slotId, item.itemName or "?", item.slot or "?"))
                        shown = shown + 1
                    end
                end
                if count > 3 then
                    Print(string.format("  ... and %d more items", count - 3))
                end
            else
                Print("|cFFFF0000No equipment data!|r")
            end
        end

    -- [DEBUG] Loot collector commands (remove before release)
    elseif msg == "lootdb" then
        if not GearScoreLootDB then
            PrintError("Loot database not initialized yet")
        else
            local count = GearScore_GetLootDBCount and GearScore_GetLootDBCount() or 0
            Print("[DEBUG] --- Loot Database ---")
            Print(string.format("Items collected: %d", count))
            Print(string.format("DB version: %s", tostring(GearScoreLootDB.version or "N/A")))
            if GearScoreLootDB.lastUpdated and GearScoreLootDB.lastUpdated > 0 then
                Print(string.format("Last updated: %d seconds ago", time() - GearScoreLootDB.lastUpdated))
            end
        end

    elseif string.find(msg, "^lootitem ") then
        local _, _, idStr = string.find(msg, "^lootitem (%d+)")
        local itemId = tonumber(idStr)
        if not itemId then
            PrintError("Usage: /gs lootitem <itemId>")
        elseif not GearScoreLootDB or not GearScoreLootDB.items or not GearScoreLootDB.items[itemId] then
            PrintError("Item #" .. itemId .. " not found in loot DB")
        else
            local item = GearScoreLootDB.items[itemId]
            Print("[DEBUG] --- Item #" .. itemId .. " ---")
            Print("Name: " .. (item.name or "?"))
            Print("Quality: " .. tostring(item.quality or "?"))
            Print("Type: " .. (item.itemType or "?") .. " / " .. (item.itemSubType or "?"))
            Print("Slot: " .. (item.equipSlot or "?"))
            Print("Bind: " .. (item.bindType or "?"))
            if item.stats then
                for stat, val in pairs(item.stats) do
                    Print("  " .. stat .. ": " .. tostring(val))
                end
            end
            if item.equip then
                for i = 1, table.getn(item.equip) do
                    Print("  Equip: " .. item.equip[i])
                end
            end
            local sourceCount = item.sources and table.getn(item.sources) or 0
            Print("Sources: " .. sourceCount .. " entries")
        end

    elseif msg == "lootlist" then
        if not GearScoreLootDB or not GearScoreLootDB.items then
            PrintError("Loot database not initialized")
        else
            Print("[DEBUG] --- All Collected Items ---")
            local count = 0
            for itemId, item in pairs(GearScoreLootDB.items) do
                count = count + 1
                local qualityColors = {
                    [0] = "|cFF9D9D9D",  -- Poor (gray)
                    [1] = "|cFFFFFFFF",  -- Common (white)
                    [2] = "|cFF1EFF00",  -- Uncommon (green)
                    [3] = "|cFF0070DD",  -- Rare (blue)
                    [4] = "|cFFA335EE",  -- Epic (purple)
                    [5] = "|cFFFF8000",  -- Legendary (orange)
                }
                local color = qualityColors[item.quality] or "|cFFFFFFFF"
                local slot = item.equipSlot or item.armorType or "?"
                Print(string.format("  %s[%d] %s|r - %s", color, itemId, item.name or "?", slot))
            end
            Print(string.format("Total: %d items", count))
        end

    elseif msg == "lootclear" then
        GearScoreLootDB = { version = 1, lastUpdated = 0, items = {} }
        Print("[DEBUG] Loot database cleared")

    elseif msg == "lootpending" then
        local count = GearScore_GetPendingCount and GearScore_GetPendingCount() or 0
        Print("[DEBUG] Pending items in retry queue: " .. count)

    elseif msg == "loottest" then
        -- Parse tooltip of currently hovered item
        local itemLink = ResolveTooltipItemLink(GameTooltip)
        if not itemLink then
            PrintError("Hover over an item first")
        else
            local parsed = GearScore_ParseItemTooltip(itemLink)
            if not parsed then
                PrintError("Could not parse item (not cached?)")
            else
                Print("[DEBUG] --- Tooltip Parse ---")
                Print("Name: " .. (parsed.name or "?"))
                Print("Slot: " .. (parsed.equipSlot or "?"))
                Print("Armor Type: " .. (parsed.armorType or "?"))
                Print("Bind: " .. (parsed.bindType or "?"))
                Print("Req Level: " .. tostring(parsed.requiredLevel or "?"))
                if parsed.stats then
                    for stat, val in pairs(parsed.stats) do
                        Print("  " .. stat .. ": " .. tostring(val))
                    end
                end
                if parsed.equip then
                    for i = 1, table.getn(parsed.equip) do
                        Print("  Equip: " .. parsed.equip[i])
                    end
                end
                if parsed.dps then
                    Print("DPS: " .. tostring(parsed.dps))
                end
            end
        end
    -- [/DEBUG]

    elseif msg == "inventory" or msg == "inv" then
        -- Show inventory status
        GearScore_ScanBags()
        local bagCount = GearScoreInventory.bags and table.getn(GearScoreInventory.bags) or 0
        local bankCount = GearScoreInventory.bank and table.getn(GearScoreInventory.bank) or 0
        Print("--- Inventory ---")
        Print(string.format("Bag items: %d unique", bagCount))
        Print(string.format("Bank items: %d unique", bankCount))
        if GearScoreInventory.bankSyncedAt then
            Print(string.format("Bank last scanned: %d seconds ago", time() - GearScoreInventory.bankSyncedAt))
        else
            Print("Bank: not scanned yet (open your bank)")
        end
        local syncStatus = (GearScoreSettings and GearScoreSettings.inventorySync ~= false) and "|cFF00FF00enabled|r" or "|cFFFF0000disabled|r"
        Print("Inventory sync: " .. syncStatus)

    elseif msg == "inventory on" then
        if not GearScoreSettings then GearScoreSettings = {} end
        GearScoreSettings.inventorySync = true
        Print("Inventory sync |cFF00FF00enabled|r")
        GearScore_ScanBags()

    elseif msg == "inventory off" then
        if not GearScoreSettings then GearScoreSettings = {} end
        GearScoreSettings.inventorySync = false
        GearScoreInventory = {}
        Print("Inventory sync |cFFFF0000disabled|r — inventory data cleared")

    elseif msg == "settings" or msg == "config" or msg == "ui" then
        if GearScoreSettingsFrame then
            if GearScoreSettingsFrame:IsVisible() then
                GearScoreSettingsFrame:Hide()
            else
                GearScoreSettingsFrame:Show()
                if GearScoreUI_UpdateStatus then
                    GearScoreUI_UpdateStatus()
                end
            end
        else
            PrintError("UI not loaded yet")
        end

    elseif msg == "help" or msg == "h" or msg == "?" then
        Print("--- Commands ---")
        Print("/gs settings - Open settings panel")
        Print("/gs scan - Manually scan and save equipped gear")
        Print("/gs stats - Show addon statistics")
        Print("/gs upgrades - List items with upgrade data")
        Print("/gs debug - Show saved data (for troubleshooting)")
        Print("/gs clear - Clear saved data")
        Print("/gs inventory - Show bag/bank inventory status")
        Print("/gs inventory on|off - Enable/disable inventory sync")
        Print("/gs help - Show this help")
        -- [DEBUG] Loot commands (remove before release)
        Print("--- Debug (Loot Collector) ---")
        Print("/gs lootdb - Show loot database stats")
        Print("/gs lootlist - List all collected items")
        Print("/gs lootitem <id> - Inspect item in loot DB")
        Print("/gs lootclear - Reset loot database")
        Print("/gs lootpending - Show retry queue size")
        Print("/gs loottest - Parse hovered item tooltip")

    else
        Print("Unknown command. Type /gs help for available commands")
    end
end

-- ============================================================================
-- INVENTORY SCANNING (Bags + Bank)
-- ============================================================================

-- Initialize inventory SavedVariable
if not GearScoreInventory then
    GearScoreInventory = {}
end

-- Default inventory sync to enabled
if GearScoreSettings and GearScoreSettings.inventorySync == nil then
    GearScoreSettings.inventorySync = true
end

-- Parse item ID from an item link string
local function GetItemIdFromLink(itemLink)
    if not itemLink then return nil end
    local _, _, itemId = string.find(itemLink, "item:(%d+)")
    if itemId then return tonumber(itemId) end
    return nil
end

-- Scan all bag contents and save to GearScoreInventory
function GearScore_ScanBags()
    if GearScoreSettings and GearScoreSettings.inventorySync == false then return end
    if not GearScoreInventory then GearScoreInventory = {} end

    local items = {}
    -- Bags 0-4: backpack (0) + 4 equipped bags
    for bag = 0, 4 do
        local numSlots = GetContainerNumSlots(bag)
        if numSlots and numSlots > 0 then
            for slot = 1, numSlots do
                local itemLink = GetContainerItemLink(bag, slot)
                if itemLink then
                    local itemId = GetItemIdFromLink(itemLink)
                    if itemId and itemId > 0 then
                        local _, count = GetContainerItemInfo(bag, slot)
                        count = count or 1
                        -- Aggregate stacks of the same item
                        if items[itemId] then
                            items[itemId] = items[itemId] + count
                        else
                            items[itemId] = count
                        end
                    end
                end
            end
        end
    end

    -- Convert to array format
    local bagItems = {}
    for itemId, count in pairs(items) do
        table.insert(bagItems, { itemId = itemId, count = count })
    end

    GearScoreInventory.character = UnitName("player")
    GearScoreInventory.realm = GetRealmName()
    GearScoreInventory.bags = bagItems
    GearScoreInventory.lastUpdated = time()
end

-- Scan bank contents and save to GearScoreInventory
-- Only callable when bank frame is open
function GearScore_ScanBank()
    if GearScoreSettings and GearScoreSettings.inventorySync == false then return end
    if not GearScoreInventory then GearScoreInventory = {} end

    local items = {}

    -- Main bank slots: In Vanilla, bank uses GetContainerItemLink with bag IDs
    -- Bank bag IDs are typically 5-11 in Vanilla (BANK_CONTAINER = -1 in some versions)
    -- Try container -1 for main bank, and 5-11 for bank bags
    local bankBags = { -1, 5, 6, 7, 8, 9, 10, 11 }

    for _, bag in ipairs(bankBags) do
        local numSlots = GetContainerNumSlots(bag)
        if numSlots and numSlots > 0 then
            for slot = 1, numSlots do
                local itemLink = GetContainerItemLink(bag, slot)
                if itemLink then
                    local itemId = GetItemIdFromLink(itemLink)
                    if itemId and itemId > 0 then
                        local _, count = GetContainerItemInfo(bag, slot)
                        count = count or 1
                        if items[itemId] then
                            items[itemId] = items[itemId] + count
                        else
                            items[itemId] = count
                        end
                    end
                end
            end
        end
    end

    -- Convert to array format
    local bankItems = {}
    for itemId, count in pairs(items) do
        table.insert(bankItems, { itemId = itemId, count = count })
    end

    GearScoreInventory.bank = bankItems
    GearScoreInventory.bankSyncedAt = time()
    GearScoreInventory.lastUpdated = time()

    DEFAULT_CHAT_FRAME:AddMessage("|cFF00FF00GearScore:|r Bank inventory scanned (" .. table.getn(bankItems) .. " items)")
end

-- Debounce timer for bag scanning
local inventoryFrame = CreateFrame("Frame")
local bagScanPending = false
local bagScanElapsed = 0

inventoryFrame:SetScript("OnUpdate", function()
    if not bagScanPending then return end
    bagScanElapsed = bagScanElapsed + arg1
    if bagScanElapsed >= 2 then
        bagScanPending = false
        bagScanElapsed = 0
        GearScore_ScanBags()
    end
end)

-- Inventory event handler
local invEventFrame = CreateFrame("Frame")
invEventFrame:SetScript("OnEvent", function()
    if event == "BAG_UPDATE" then
        -- Debounce: BAG_UPDATE fires many times during looting
        bagScanPending = true
        bagScanElapsed = 0

    elseif event == "BANKFRAME_OPENED" then
        -- Bank is open — scan it now
        GearScore_ScanBank()

    elseif event == "PLAYERBANKSLOTS_CHANGED" then
        -- Items moved within bank while it's open
        GearScore_ScanBank()
    end
end)

invEventFrame:RegisterEvent("BAG_UPDATE")
invEventFrame:RegisterEvent("BANKFRAME_OPENED")
invEventFrame:RegisterEvent("PLAYERBANKSLOTS_CHANGED")

-- Register slash commands
SLASH_GEARSCORE1 = "/gs"
SLASH_GEARSCORE2 = "/gearscore"
SlashCmdList["GEARSCORE"] = HandleSlashCommand

-- ============================================================================
-- INITIALIZATION
-- ============================================================================

-- Initial bag scan on load
GearScore_ScanBags()

PrintDebug("Loaded! Type /gs help for commands")
